export const domElements = {
    tabButtons: document.querySelectorAll('.tab'),
    tabContents: document.querySelectorAll('.tab-content'),
    subjectSelect: document.getElementById('subject-select'),
    addSubjectBtn: document.getElementById('add-subject-btn'),
    importDataBtn: document.getElementById('import-data-btn'),
    exportDataBtn: document.getElementById('export-data-btn'),
    importFileInput: document.getElementById('import-file'),
    addTopicBtn: document.getElementById('add-topic-btn'),
    addFlashcardTopicBtn: document.getElementById('add-flashcard-topic-btn'),
    subjectModal: document.getElementById('subject-modal'),
    topicModal: document.getElementById('topic-modal'),
    newSubjectNameInput: document.getElementById('new-subject-name'),
    newSubjectDescInput: document.getElementById('new-subject-description'),
    saveSubjectBtn: document.getElementById('save-subject-btn'),
    newTopicNameInput: document.getElementById('new-topic-name'),
    newTopicDescInput: document.getElementById('new-topic-description'),
    saveTopicBtn: document.getElementById('save-topic-btn'),
    closeModalBtns: document.querySelectorAll('.close-modal'),
    contentTypeBtns: document.querySelectorAll('.content-type-btn'),
    addQuestionForm: document.getElementById('add-question-form'),
    addFlashcardForm: document.getElementById('add-flashcard-form'),
    questionTypeSelect: document.getElementById('question-type-select'),
    questionTopicSelect: document.getElementById('question-topic-select'),
    questionTextInput: document.getElementById('question-text-input'),
    optionsInputContainer: document.getElementById('options-input-container'),
    optionsList: document.getElementById('options-list'),
    addOptionBtn: document.getElementById('add-option-btn'),
    correctAnswerSelect: document.getElementById('correct-answer-select'),
    keywordsContainer: document.getElementById('keywords-container'),
    keywordsInput: document.getElementById('keywords-input'),
    explanationInput: document.getElementById('explanation-input'),
    saveQuestionBtn: document.getElementById('save-question-btn'),
    flashcardTopicInput: document.getElementById('flashcard-topic-input'),
    flashcardFrontInput: document.getElementById('flashcard-front-input'),
    flashcardBackInput: document.getElementById('flashcard-back-input'),
    saveFlashcardBtn: document.getElementById('save-flashcard-btn'),
    filterContentType: document.getElementById('filter-content-type'),
    filterContentTopic: document.getElementById('filter-content-topic'),
    contentSearch: document.getElementById('content-search'),
    contentList: document.getElementById('content-list'),
    questionTypeSelectElement: document.getElementById('question-type'),
    topicSelectElement: document.getElementById('topic-select'),
    questionText: document.getElementById('question-text'),
    optionsContainer: document.getElementById('options-container'),
    shortAnswerContainer: document.getElementById('short-answer-container'),
    shortAnswerInput: document.getElementById('short-answer'),
    checkAnswerButton: document.getElementById('check-answer'),
    nextQuestionButton: document.getElementById('next-question'),
    feedbackElement: document.getElementById('feedback'),
    currentQuestionElement: document.getElementById('current-question'),
    totalQuestionsElement: document.getElementById('total-questions'),
    progressFill: document.getElementById('progress-fill'),
    progressPercent: document.getElementById('progress-percent'),
    flashcardTopicSelectElement: document.getElementById('flashcard-topic-select'),
    prevFlashcardButton: document.getElementById('prev-flashcard'),
    nextFlashcardButton: document.getElementById('next-flashcard'),
    flashcardCounter: document.getElementById('flashcard-counter'),
    currentFlashcard: document.getElementById('current-flashcard'),
    flashcardFrontText: document.getElementById('flashcard-front-text'),
    flashcardBackText: document.getElementById('flashcard-back-text'),
    markKnownButton: document.getElementById('mark-known'),
    markReviewButton: document.getElementById('mark-review'),
    totalAnsweredElement: document.getElementById('total-answered'),
    totalCorrectElement: document.getElementById('total-correct'),
    accuracyElement: document.getElementById('accuracy'),
    topicStatsElement: document.getElementById('topic-stats'),
    historyTableBody: document.getElementById('history-table-body'),
    performanceChart: document.getElementById('performance-chart'),
};

export function openModal(modal) {
    document.querySelectorAll('.modal').forEach((m) => (m.style.display = 'none'));
    modal.style.display = 'block';
}

export function closeAllModals() {
    document.querySelectorAll('.modal').forEach((modal) => {
        modal.style.display = 'none';
    });
}